//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LexicoSintatico {
    using System;
    
    
    /// <summary>
    ///   Uma classe de recurso de tipo de alta segurança, para pesquisar cadeias de caracteres localizadas etc.
    /// </summary>
    // Essa classe foi gerada automaticamente pela classe StronglyTypedResourceBuilder
    // através de uma ferramenta como ResGen ou Visual Studio.
    // Para adicionar ou remover um associado, edite o arquivo .ResX e execute ResGen novamente
    // com a opção /str, ou recrie o projeto do VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource1 {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource1() {
        }
        
        /// <summary>
        ///   Retorna a instância de ResourceManager armazenada em cache usada por essa classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LexicoSintatico.Resource1", typeof(Resource1).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Substitui a propriedade CurrentUICulture do thread atual para todas as
        ///   pesquisas de recursos que usam essa classe de recurso de tipo de alta segurança.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Input Accepted.
        /// </summary>
        internal static string Accepted {
            get {
                return ResourceManager.GetString("Accepted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a ######Lexical Analysis######.
        /// </summary>
        internal static string AnaLex {
            get {
                return ResourceManager.GetString("AnaLex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Lexical Analysis.
        /// </summary>
        internal static string AnaLex2 {
            get {
                return ResourceManager.GetString("AnaLex2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a ######Syntactic Analysis######.
        /// </summary>
        internal static string AnaSint {
            get {
                return ResourceManager.GetString("AnaSint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a &lt;Attribute, Symbol&gt;.
        /// </summary>
        internal static string AtrSimb {
            get {
                return ResourceManager.GetString("AtrSimb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a ###End of Processing###.
        /// </summary>
        internal static string End {
            get {
                return ResourceManager.GetString("End", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a The file could not be read:.
        /// </summary>
        internal static string ErroArquivoNaoLido {
            get {
                return ResourceManager.GetString("ErroArquivoNaoLido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Error at .
        /// </summary>
        internal static string ErrorAt {
            get {
                return ResourceManager.GetString("ErrorAt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Generating file AnaliseLexica.txt.
        /// </summary>
        internal static string GerAnaLex {
            get {
                return ResourceManager.GetString("GerAnaLex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Generating file AnaliseSintatica.txt.
        /// </summary>
        internal static string GerAnaSint {
            get {
                return ResourceManager.GetString("GerAnaSint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a  Line .
        /// </summary>
        internal static string Linha {
            get {
                return ResourceManager.GetString("Linha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Press 0 to see both the Lexical and Syntactic Analysis.
        /// </summary>
        internal static string Menu0 {
            get {
                return ResourceManager.GetString("Menu0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Press 1 to see the Lexical Analysis Only.
        /// </summary>
        internal static string Menu1 {
            get {
                return ResourceManager.GetString("Menu1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Press 2 to see the Syntactic Analysis Only.
        /// </summary>
        internal static string Menu2 {
            get {
                return ResourceManager.GetString("Menu2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Press 0 to create output files.
        /// </summary>
        internal static string Menu3 {
            get {
                return ResourceManager.GetString("Menu3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Press 1 to display the output in the console.
        /// </summary>
        internal static string Menu4 {
            get {
                return ResourceManager.GetString("Menu4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Default = 0.
        /// </summary>
        internal static string MenuDef {
            get {
                return ResourceManager.GetString("MenuDef", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Type the file name to be tested.
        /// </summary>
        internal static string NomeArquivo1 {
            get {
                return ResourceManager.GetString("NomeArquivo1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a This file has to be in the same folder as the binary.
        /// </summary>
        internal static string NomeArquivo2 {
            get {
                return ResourceManager.GetString("NomeArquivo2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Possible Productions:.
        /// </summary>
        internal static string ProdPoss {
            get {
                return ResourceManager.GetString("ProdPoss", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Input Rejected.
        /// </summary>
        internal static string Rejected {
            get {
                return ResourceManager.GetString("Rejected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a  Symbol .
        /// </summary>
        internal static string Simb {
            get {
                return ResourceManager.GetString("Simb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Expected Symbols:.
        /// </summary>
        internal static string SimbEsperado {
            get {
                return ResourceManager.GetString("SimbEsperado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Press any key to continue to the Syntactic Analisis.
        /// </summary>
        internal static string Stop {
            get {
                return ResourceManager.GetString("Stop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Symbols Table.
        /// </summary>
        internal static string TabSimb {
            get {
                return ResourceManager.GetString("TabSimb", resourceCulture);
            }
        }
    }
}
